name: Bug Report
description: Report a problem with pick-lsp-formatter
labels: [bug]
body:
  - type: textarea
    attributes:
      label: "Description"
      description: "Describe the problem you are reporting."
      placeholder: "A clear and concise description of the bug"
    validations:
      required: true
